# Generated by Django 3.0.8 on 2020-07-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_personal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
